### ISSUE TITLE
Nested panels resize issue

### ISSUE THREAD

**Issue by Baart** [angular-ui/ui-layout#102]
Having an issue when trying to resize nested panels.

Here the plunker and the step to reproduce:

http://plnkr.co/edit/QsB0b1?p=preview

To reproduce:
 - Move splitbar between BB and CC, all will be adjusted.
 - Move splitbar between  AA and BB to the left.
 - Size of CC is not recalculated leading to a visible hole

Is there a way of doing this correctly ?

**Comment by SomeKittens** [comment]
Thanks for the plunker, makes debugging a lot easier.  The sub-layout should ensure it's taking up the entire space, even on resize.
