### ISSUE TITLE
Why is z-index=1010 for splitbar?

### ISSUE THREAD

**Issue by Jakobovski** [angular-ui/ui-layout#103]
Hi,

I am having some issues with the split-bar being above some other elements. I am wondering why the z-index on the split bar is 1010 and what are the consequences of setting it to 0?

Thanks

**Comment by SomeKittens** [comment]
It's set to such a high number so other elements don't appear on top of it.  The assumption is that the developer would want it at the top.  You are free to override this as you wish.
