### ISSUE TITLE
data-size, data-min-size, ... should work as size, min-size, ...

### ISSUE THREAD

**Issue by beradrian** [angular-ui/ui-layout#108]

**Comment by BobbieBarker** [comment]
As self explanatory as you feel your title may be, it would be far more constructive if you posted an issue fully describing what you think is broke, or how you think things should be different.

**Comment by j--w** [comment]
Plunker to reproduce: http://plnkr.co/edit/eBmiZqARspptaTD3wMgT?p=preview

**Comment by yanivefraim** [comment]
Cool, I'm working on this one!
