### ISSUE TITLE
Parameterized Flow (Row/Column)

### ISSUE THREAD

**Issue by bbranden** [angular-ui/ui-layout#11]
I've been looking in layout options for an upcoming product, and what you have so far is pretty slick.  I agree with issue #3 ... the ability to set/persist width & height on each split is key.

Beyond that, I'd like a hook to parameterize the flow option... meaning a way to toggle the split from a Row to Column, and visa-versa.  The link below takes you to an example showing how this could work.

http://plnkr.co/edit/igJXFGghO3eKHPQ23Jq2?p=preview

If you inspect the DOM, you'll see that the DOM elements are changing... but only the splitbar is updating.

**Comment by vontdeux** [comment]
is the parameterized flow option enabled? since this was closed?
unable to find a way to toggle between flow : column & row programatically.

**Comment by zoiii** [comment]
Hello. Is there any update on toggle between row/column ??

**Comment by umdstu** [comment]
+1 Bump.

This doesn't appear to work anymore. I'm sure a lot has changed since 0.0.0.
