### ISSUE TITLE
Trying to make angular-ui-layout work with SystemJS/JSPM 

### ISSUE THREAD

**Issue by nicklasb** [angular-ui/ui-layout#112]
The npm package (-requirejs) has an index.js-file that requires the ui-layout.css via `require('./src/ui-layout.css')`. 

However, that doesn't work with SystemJS, as css-files are imported using its css-module via the addition of an exclamation mark, `require('./src/ui-layout.css!')`. 

As the packaging of this component involves different branches and so on, I am a bit unsure of how or where to fix this...

**Comment by SomeKittens** [comment]
Hi, new maintainer here.  Trying to get up to speed.  Right now it only works with Bower, so I'd like to get NPM on board first, and then look into other packages, so don't hold your breath.

PRs would be very welcome!

**Comment by nicklasb** [comment]
The npm package works as is with RequireJS, it is just a nuance that keeps it from working with SystemJS as well.

Usually one basically publish exactly the same files to bower and npm, and then npm/bower just looks in their respective config files, however, with this library, there are completely different structure and kept in different branches.  I am not sure why, I don't particularly see any really big upside with that. 

I would propose using gulp-umd or something to make the library more loadable.

**Comment by nicklasb** [comment]
WRT PR:s, absolutely, but I am not sure where to put stuff.

**Comment by SomeKittens** [comment]
Yeah, that's currently my big hangup - trying to figure out how to normalize the build process without breaking everything for everyone.  I'm hesitant to make any major changes without fully understanding what I'm doing.  Thanks again and I'll see what I can do

**Comment by nicklasb** [comment]
I would try to do like everyone else does, i.e. not make it complicated and just have one setup that has both bower.json and package.json. 
And then as I said, just use gulp-umd to make it load properly.

Honestly, I would just make it the way you want and then make a minor but breaking release (like 1.1) and guide people through any changes in the docs.
I mean, it is not like it will force them to do any major rewrites, at most it is changing an url.

**Comment by robwormald** [comment]
probably the least invasive fix for this would be using the jspm property in the package.json:

```js
//jspm overrides
"jspm" : {
  "format" : "global",
  "directories" : {
    //ignores everything not in src
    "lib" : "src"
  },
  "main" : "ui-layout"
}
```
that way it doesn't mess with the browserify config at all and simply loads the normal global version. you can test this out when installing:
```
jspm install angular-ui-layout -o "{ format: "global", ...etc }"
```
@nicklasb try it out and see if you can get it working, then its an easy PR.

**Comment by nicklasb** [comment]
I agree, this is probably the best way. Also, in the nextisch versions jspm will support .css-loading from the package.json as well.
I will try it.

**Comment by nicklasb** [comment]
It seems the npm-package has changed into a more normal structure now, it looks like it might work acceptably as is now, actually. This might then not be needed. I'll test a little and get back to you.

**Comment by nicklasb** [comment]
Hm, It appears that that doesn't work:
```bash
$ jspm install angular-ui-layout -o { "format" : "global", "directories" : { "lib" : "src"}, "main" : "ui-layout"}

err  ReferenceError: src is not defined
         at eval (eval at <anonymous> (node_modules/jspm/cli.js:268:50), <anonymous>:1:43)
         at node_modules/jspm/cli.js:268:30
         at Object.<anonymous> (node_modules/jspm/cli.js:584:3)
         at Module._compile (module.js:456:26)
         at Object.Module._extensions..js (module.js:474:10)
         at Module.load (module.js:356:32)
         at Function.Module._load (module.js:312:12)
         at Module.require (module.js:364:17)
         at require (module.js:380:17)
         at Liftoff.<anonymous> (/usr/local/lib/node_modules/jspm/jspm.js:33:5)


```
I don't know how to get around the "src is not defined"-error.

**Comment by robwormald** [comment]
You need to wrap it in quotes - "{foo:'bar'}"

**Comment by nicklasb** [comment]
Sorry. My god, that was stupid. :-)
It works perfectly, I second that this should be added to package.json.

**Comment by SomeKittens** [comment]
Splendid!  Open a PR and I'll bring it right in.

**Comment by SomeKittens** [comment]
JSPM details added to package.json in 199429cfbc1cc7e7a2471cb4e44c2315910fbe06
