### ISSUE TITLE
Is dependency on "raf" in bower.json valid?

### ISSUE THREAD

**Issue by mackler** [angular-ui/ui-layout#114]
I'm no bower expert, but my reading of [what appears to be the specification](http://bower.io/docs/creating-packages/#dependencies) suggests that [this project's `bower.json` file](https://github.com/angular-ui/ui-layout/blob/master/bower.json#L20) violates the specification.

[The specification](http://bower.io/docs/creating-packages/#dependencies) says that each key of the `dependency` object must be "a valid name," by which I understand it to mean name of a bower package.  [Line 20 of `bower.json`](https://github.com/angular-ui/ui-layout/blob/master/bower.json#L20) reads:

    "raf": "https://gist.githubusercontent.com/paulirish/1579671/raw/3d42a3a76ed09890434a07be2212f376959e616f/rAF.js"

Yet when I run `bower info raf` I get:

    bower                        ENOTFOUND Package raf not found

and I would conclude that if there is no package named `raf` then `raf` is not a valid name, and its inclusion in this project's `bower.json` violates the specification.

I noticed this because I tried to initiate the automated process of creating a [bower WebJar](http://www.webjars.org/bower) for this project, but the process failed, and after reporting this to the WebJars project, owner James Ward [responded by saying that this project's `bower.json` file is invalid](https://github.com/webjars/webjars/issues/1173#issuecomment-134595743), though he gave no more details.

I would be happy to submit a pull-request that removes that dependency on `raf` from the `bower.json` file, but I don't understand its purpose there enough to know whether doing so might have some other negative consequence, thus I am creating this issue to request information.

**Comment by SomeKittens** [comment]
If you follow the GH link, you'll find that `raf` is a polyfill for `requestAnimationFrame` so that ui-layout is compatible with IE9.

On the other hand, we've got a warning for users to include the polyfill themselves right at the start of our README.  One of those two will have to change.

(new maintainer picking this up after ~6 months of inactivity, still learning the ropes).

**Comment by mackler** [comment]
Thanks for the quick response and explanation.  I'm unclear whether or not you're saying the content of this project's `bower.json` file is valid.

**Comment by SomeKittens** [comment]
If this issue is about bower validity, I'll close it.  We have more serious problems than that.  If this issue is about how the current system works (and from my perspective, we're providing false/misleading info, which is a *very bad thing*), then we need to fix it.

**Comment by wesleycho** [comment]
@SomeKittens some people use libraries like wiredep, grunt-injector, or gulp-inject to automatically inject dependency scripts into their page - in this case, the inclusion should be at user's discretion with warning in the README.

**Comment by SomeKittens** [comment]
Alright, thanks for the response @wesleycho.  I'll pull that out of `bower.json` when I get some breathing room later today.

**Comment by mackler** [comment]
> If this issue is about how the current system works...then we need to fix it.

The reason I opened this issue is because I want to create a bower WebJar so I can use this package in my maven project. My repeated references to validity are based on a presumption that the possible-invalidity in question is preventing the WebJar processor from working and that if that is the case then removing such invalidity would allow the WebJar processor work.  However, if the file is valid then my presumption is false and I need to be looking for a solution elsewhere.  I apologize if I should have described the issue in more practical terms.

**Comment by SomeKittens** [comment]
@mackler that's more clear, thanks.  I tend to be allergic to those who go around nitpicking OS projects.

**Comment by SomeKittens** [comment]
aaaand looking back you did mention that in the OP.  Welp, my bad.

**Comment by SomeKittens** [comment]
Turns out that was there because the tests fail without a RAF shim.  I've switched us to a RAF shim that's actually in the registry (and hopefully won't break WebJar) and also moved it to devDeps.

**Comment by mackler** [comment]
Success!  Version 1.1.0 now has [its own maven artifact](http://search.maven.org/#artifactdetails%7Corg.webjars.bower%7Cangular-ui-layout%7C1.1.0%7Cjar).  Thank you for the fix and for your efforts maintaining this project.
