### ISSUE TITLE
ui-layout-container no longer works as an element name

### ISSUE THREAD

**Issue by groberts9** [angular-ui/ui-layout#115]
I am lucky not to need to support IE, so I use directives as elements. 

However the 1.1.0 fix for *ng-if* (issue #84, which has been rolled into this release) assumed *ui-layout-container*  is always used as an element attribute.

This limitation is caused by the following code:

    ctrl.isLayoutElement = function(element) {
      return element.hasAttribute('ui-layout-container') || element.hasAttribute('ui-splitbar');
    };

The limitation can be removed by the following change:

    ctrl.isLayoutElement = function(element) {
      return element.hasAttribute('ui-layout-container') || element.nodeName === 'UI-LAYOUT-CONTAINER' || element.hasAttribute('ui-splitbar');
    };

**Comment by SomeKittens** [comment]
Good catch.  Would you mind opening a PR?  Otherwise I can get to that (maybe) tonight.

**Comment by SomeKittens** [comment]
Add this test to `uiLayoutCtrl.spec.js` - it should fail currently, and pass with the patch applied:

```
describe('ctrl functions', function () {
    it('isLayoutElement', function () {
      var uic = $controller('uiLayoutCtrl', {
        $scope: scope,
        $attrs: {},
        $element: angular.element('<div></div>')
      });

      var attrContainer = document.createElement('div');
      attrContainer.setAttribute('ui-layout-container', '');

      var attrSplitbar = document.createElement('div');
      attrSplitbar.setAttribute('ui-splitbar', '');

      var tagContainer = document.createElement('ui-layout-container');

      var notUiEl = document.createElement('div');

      expect(uic.isLayoutElement(attrContainer)).toEqual(true);
      expect(uic.isLayoutElement(attrSplitbar)).toEqual(true);
      expect(uic.isLayoutElement(tagContainer)).toEqual(true);
      expect(uic.isLayoutElement(notUiEl)).toEqual(false);
    });
  });
