### ISSUE TITLE
ng-if causes incorrect layout if previous container is collapsed when changed to false

### ISSUE THREAD

**Issue by groberts9** [angular-ui/ui-layout#116]
Using 1.1.0 which includes fix for *ng-if* (issue #84), and a layout similar to the following:

```
<div ui-layout>
  <div ui-layout-container>...</div>
  <div ui-layout-container ng-if="toggleVariable">...</div>
</div ui-layout>
```

1. With *toggleVariable* set to true, collapse left container display using chevron button on the splitbar
2. Set *toggleVariable* to false, so that right container and splitbar are removed from DOM.
3. Set variable again so right container and splitbar are recreated.
4. Collapse display of left or right container; the containers will have the wrong size.

The problem is easy to fix by changing the *else* clause in *ctrl.removeContainer* as follows, when passed a splitbar container argument:

        } else {
          ctrl.containers[index - 1].collapsed = false;  // fix for potentially collapsed containers
          numOfSplitbars--;
        }
  
Please accept my apologies for not identifying this problem with the original fix before inclusion in the release branch, which was due to commercial priorities.

**Comment by SomeKittens** [comment]
No need to apologize.  I'm new to maintaining, still bumbling around.  Good catch, glad you've found a fix.

**Comment by danielpquinn** [comment]
Third times a charm right? The following JS Bin demonstrates the fix: https://jsbin.com/sitoha/edit?html,output

**Comment by SomeKittens** [comment]
Thanks again @groberts9 for the report & detailed repro steps.

**Comment by ice-blaze** [comment]
I think I found a bug, when the element with the ng-if is at the first place of the row or column, and have the min/max-size set, when it disappear the container next to it will inherit the size attributes.

https://jsbin.com/cotobep/edit?html,output

**Comment by SomeKittens** [comment]
@ice-blaze yeah, new issue for that.
