### ISSUE TITLE
Layout with fixed north pane.

### ISSUE THREAD

**Issue by nicolasr75** [angular-ui/ui-layout#117]
I want to have a layout with fixed top pane for a toolbar and two horizontally resizable panes below it. At first I thought I simply put ui-layout in a separate div below my toolbar but that doesn't seem to work. The ui-splitbar of the resizable panes always takes the full height and so overlaps my toolbar.

Then I tried to create a nested layout (top, left, right panes) and put my toolbar in the top pane. As someone suggested in one of the other issue posts I tried to set the horizontal divider that divides the top pane and the other panes to dividerSize=0 but does not seem to have effect. I can set it to 1, for example, but not to 0. Any idea how to achieve this?

**Comment by miriam-yodlr** [comment]
If I understand what you want correctly, here is an example https://rooms.getyodlr.com/layout. This leaves space at the top by adding a class to the top level div
`<div class="top-stretch" ui-layout="{flow: 'column'}">`
and then styling it to leave space for your toolbar

    .top-stretch {
        top: 46px; /* or whatever height your toolbar is*/
    }

The classes "top-stretch stretch ui-layout-column" get added to that element. The .stretch class has 

    .stretch {
        position: absolute;
        top: 0; /*you need your CSS to over ride this with the height of your toolbar*/
    }

**Comment by nicolasr75** [comment]
Great, thank you very much. Although I had to use
.top-stretch {
    top: 46px !important;
}

**Comment by miriam-yodlr** [comment]
You are probably loading your UI-Layout CSS after your own CSS. If yours came after, you probably wouldn't need !important.  Alternately, you can see the strength of that divs "top: 0" rule and override it by using a longer selector, .mydiv .bla .topstretch {....

**Comment by nicolasr75** [comment]
Ahh, of course. Thanks for the pointer.

**Comment by SomeKittens** [comment]
thanks, @miriam-yodlr for helping out here.
