### ISSUE TITLE
Trying to set uiLayoutContainer's size via controller varaible

### ISSUE THREAD

**Issue by nitech** [angular-ui/ui-layout#124]
I am trying to set the uiLayoutContainer's size attribute from a controller's variable like thus: 

```javascript
$scope.defaultWidth = "200px"; 
```
```html
<div id="activities" ui-layout-container size="defaultWidth"></div>
```

But it doesn't work. What am I doing wrong? Is it supposed to work this way?

**Comment by j--w** [comment]
Should be:
```html
<div id="activities" ui-layout-container size="{{defaultWidth}}"></div>
```

**Comment by nitech** [comment]
You are completely right. My lack of Angular knowledge. Thank you :-)

However, when I resize the window after having pulled the split bar, the layout jumps back to the initial sizes. It happens in your plnkr too. How can I avoid that?

**Comment by SomeKittens** [comment]
@nitech no worries.  Looking into #100.
