### ISSUE TITLE
Programmatically collapse/expand a container

### ISSUE THREAD

**Issue by dungvu-qe** [angular-ui/ui-layout#128]
Dear dev,

Could you support binding collapsed option on ui-layout-container control.
Thanks

**Comment by SomeKittens** [comment]
What do you mean by "Binding collapsed option"?  How would you expect such a feature to work?

**Comment by dungvu-qe** [comment]
In demo/demo2.html, this properties not work in ver 1.2.0

<body ng-controller="DemoController">
  <div ui-layout="config">
   ...
    <div ui-layout-container collapsed="false">Two</div>
    ...
  </div>
</body>

And we try to use binding this via:
 <div ui-layout-container collapsed="{{tabCollaped}}">Two</div>
--> not work, too.

**Comment by pisquared** [comment]
I'd also love this feature!
Is it somewhere on the roadmap?

**Comment by SomeKittens** [comment]
@pisquared No one is actively working on it currently.  It's yours for the taking.

**Comment by Tooa** [comment]
I'm also interested in this feature. Could you give some good starting points in the code? How could such a feature roughly be implemented? Maybe I will pick it up then. Best Uli

**Comment by petrsimon** [comment]
Hi, I've started using ui-layout yesterday and really needed this. Please have a look and let me know what you think. petrsimon/ui-layout@f01b492cf103069439e65ab7473a979ab46b9496
I haven't created a demo, but it's pretty straightforward. Just add `collapsed` attribute to the `ui-layout-container` you want to control and toggle the value.
```javascript
$scope.layout = {
    toolbar: false,
    statusbar: true
}
```

```html
<div ui-layout-container data-collapsed="layout.toolbar"></div>
<div ui-layout-container data-collapsed="layout.statusbar"></div>
```

**Comment by Tooa** [comment]
I would advice you to do a pull request. This way others can find and comment this feature and don't have to scan the Github whole issue list. Once I'm at home, I will test it and give you feedback. Thanks for taking this!

**Comment by petrsimon** [comment]
OK, thanks. I was planning to, but I thought that people who are watching this might want to have a look first. Also, haven't used/tested it much, but so far so good. Will create the pull request in a minute.

**Comment by Tooa** [comment]
> Also, haven't used/tested it much, but so far so good.

You can do this later, when you have the time and then just simply squash your commits.  Also make sure you follow the "Commit Message Guidelines" [1]. 

[1] https://github.com/angular/angular/blob/master/CONTRIBUTING.md
