### ISSUE TITLE
UI-layout stretches to encompass entire body

### ISSUE THREAD

**Issue by nicklasb** [angular-ui/ui-layout#135]
Hi,
Even if I contain it in a div, it seems to affect the whole page, for example it stretches its background of the entirety of the page, hiding, for example, the background of a header.
Is it impossible to contain it *completely* within a `<div>`, for example?

**Comment by j--w** [comment]
UI-Layout relies on absolute positioning, so if you want it to be constricted to the parent div, throw position: relative; on the container. See http://plnkr.co/edit/d7sNP6YcoT4BbCs7HPUC?p=preview

**Comment by nicklasb** [comment]
Ok, that works, the only thing is that one have to handle the sizing someway.
Thanks!

**Comment by j--w** [comment]
What do you mean by handling the sizing some way? If you post a plunker demonstrating your issue I may be able to help.

**Comment by nicklasb** [comment]
Well, if I set it to relative or static it won't fill out the parent div, as the .stretch-class makes it go absolute again in some way. 
So now I am making a small js-resizing-snippet that resizes it on init and window.resize.

**Comment by j--w** [comment]
Perhaps I'm missing something but you should be wrapping the entire ui-layout structure in the div that you want the size to conform to. Don't put position relative on the ui-layout div, put it on it's container:
```html
<div style="width:500px; height:500px; position: relative;">
   <div ui-layout  >...</div>
</div>
```

Does that make sense?

**Comment by nicklasb** [comment]
Nope, you are right, that works.
But still, the widths are hard coded, which doesn't cover many use cases.

**Comment by j--w** [comment]
The dimensions don't need to be hardcoded, I just placed them for illustrative purposes, all of the dimensions will be inherited as long as the position: relative; is there.

**Comment by nicklasb** [comment]
That is not my experience, in fact, if you remove them in the plunkr, it disappears.
Interestingly, it only seems to be related to the width, that is the only one I need to fix.

**Comment by nicklasb** [comment]
Edited the above, mistakenly wrote width.

**Comment by j--w** [comment]
Sorry I lied about inheriting height, it will need a hight specified whether it is height: inherit; or height: 100%; . This is all just standard CSS though, nothing to do with ui-layout itself.

**Comment by nicklasb** [comment]
Ok, then thats it. That works in the plunkr but not in my application, now I got something to debug, thanks!

**Comment by nicklasb** [comment]
For posterity: 
The reason that didn't work for me was because the directive that contained the ui-layout was inside a angular view.
The solution I chose(actually written in typescript but for the quickie i did not use any trick) was to:

1 . Create a resize function that subtracts all other elements
```js
    var resizeNodes=function() {
        $("#nodesContainer").height($(window).height() - $("#footerDiv").height() - $("#menuDiv").height())
    };
```

2 . Associate the route with a controller:
```js
    app.config(($routeProvider) => {
        $routeProvider
            .when('/admin', {
                templateUrl: 'views/admin.html',
                controller: "AdminCtrl"
            })
...other routes ....
            })
            .otherwise({
                redirectTo: '/'
            });
    });
```
3 . Create the controller, and in i first call the resize function on initialization, and then connect a listener to the window.resize function:
```js
    app.controller('AdminCtrl', ["$scope", "$timeout", function($scope, $timeout) {
        $timeout(function () {
            // Set height
            resizeNodes();
            $(window).resize(function(){
                resizeNodes();
            })
        });
    }]);

**Comment by SomeKittens** [comment]
Awesome, thanks for the addition to the knowledge base!  You might want to write that up as a StackOverflow question/answer for better visiblity (and post it here if you do, I'll upvote).

oh, and +1 for TypeScript!

**Comment by nicklasb** [comment]
Ok, did that:
http://stackoverflow.com/questions/32637558/how-do-i-make-angular-ui-layout-stay-within-its-container-if-its-in-an-angular

**Comment by nicklasb** [comment]
Didn't have reputation enougt to add the angular-ui-layout-tag, though.

**Comment by j--w** [comment]
I don't have enough either. @SomeKittens how's your SO rep? Are you able to add the tag? It's 1500 I think.

**Comment by nicklasb** [comment]
As it would appear, @SomeKittens [might be our man](http://stackoverflow.com/users/1216976/somekittens). :-)

**Comment by SomeKittens** [comment]
@nicklasb have some upvotes.  Added `ui-layout` tag instead - not quite sure we're big enough to have our own tag.

**Comment by nicklasb** [comment]
Actually..you added angular-ui..but I suppose that was what you meant?

**Comment by SomeKittens** [comment]
yep, sorry...
