### ISSUE TITLE
Delete a pane make the layout bug

### ISSUE THREAD

**Issue by ice-blaze** [angular-ui/ui-layout#139]
My columns are linked to an array. If I delete a pane which don't touch the border, there will be a glitch.

http://embed.plnkr.co/Sku5ziIGKw5iPGNJSanJ/preview

**Comment by SomeKittens** [comment]
Thanks for the repo!  Weird bug, thanks for the find.

**Comment by ice-blaze** [comment]
Maybe a precision, the version of the UI.Layout on the plunker isn't the last one. If you are using the last version there is something more. When you drag the split bar, you can't leave it. I don't know if these bugs are related.

**Comment by SomeKittens** [comment]
I'm getting the same problem with latest UI-layout as show in in the original Plunkr

**Comment by pheonixblade9** [comment]
This is also resolved by adding a `track by` clause to the `ng-repeat` as in the other bug https://github.com/angular-ui/ui-layout/issues/142

**Comment by ice-blaze** [comment]
Well done sir.
