### ISSUE TITLE
ui-layout corrupts sticky footer

### ISSUE THREAD

**Issue by GregorFey** [angular-ui/ui-layout#144]
Hi,
i tried to add a static header and a sticky footer to the ui-layout demo. This results in some strange output. Look at http://plnkr.co/edit/qRqOx5lCFkwgI8u0pNyr for a demo.

Any ideas where i went wrong? Every hint would be appreciated.

Thanks in advance...

**Comment by ice-blaze** [comment]
It's not the best solution but with CSS and absolute position you can have a workaround : http://plnkr.co/edit/05pxAZU2q7puMejSSA7Q?p=preview

I hope it helps until someone show us the real power of CSS.

**Comment by GregorFey** [comment]
Thanks for your solution, ice, 

I think it will work for my needs for now. 

It may take some time till i'll start my research, but i'll post my solution if i'll find a more flexible one. 

Regards...
