### ISSUE TITLE
question of 1px

### ISSUE THREAD

**Issue by dohkoxiaozu** [angular-ui/ui-layout#147]
```html
<ui-layout options="{dividerSize:'0'}">
    <div ui-layout-container size="88%"></div>
    <div ui-layout-container size="12%"></div>
</ui-layout>
```

question:
first div(height) + second div(height) < parent div(height)
1px has gone, why?

i try to find the answer in the source code, and i find function converToPixels use floor of Math API, why?

**Comment by SomeKittens** [comment]
It's better to be one pixel smaller than your parent container instead of one pixel bigger (which could cause overflow issues)

**Comment by dohkoxiaozu** [comment]
but to use round of Math API, the sum of their pixel is equal to parent pixel, isn't it?

**Comment by SomeKittens** [comment]
Rounding is hard with floating point.  This way guarantees we won't overflow.

**Comment by dohkoxiaozu** [comment]
even though i know your intent with this design, but can it make a config to solve the 1px? 
I admit that I have obsessive-compulsive disorder...
