### ISSUE TITLE
Respect max-size when toggle arrows are clicked

### ISSUE THREAD

**Issue by lukewendling** [angular-ui/ui-layout#148]
Maybe I misunderstand the intent of the toggle arrows but the max-size setting works when sliding the panels, but max-size is not respected when the toggle buttons are used. Is this the desired behavior?

**Comment by SomeKittens** [comment]
Yes, this is correct, toggle means "remove this pane from the page"

**Comment by lukewendling** [comment]
Ok, thanks @SomeKittens. Do u know if there's a way to initially collapse a pane, when the page first loads?

**Comment by SomeKittens** [comment]
I think that's an outstanding issue
