### ISSUE TITLE
Issue with UI-Select is showing beneath the container.

### ISSUE THREAD

**Issue by azeyad** [angular-ui/ui-layout#155]
I have a two rows layout, I am using UI-Select in one container(first row) and a grid in the second container(second row), the problem is when I open the combobx it is hidden under the grid container and not showing above it as it should, though if i used an ordinary select tag with choices it opens just fine
I have create a plunker for you as well
http://plnkr.co/edit/g33lRDyWcALTOCWmVGwl

**Comment by azeyad** [comment]
I tried to manipulate the z-index a lot but with no luck, anyone faced something like this before?

**Comment by petrsimon** [comment]
Haven't you find anything at ui-select. I'm sure if you search ui-select issues, you'll find something about this. I think has to do not only with z-index, but also overflow. I remember that jquery ui-layout, which I've used before had a setting for this. Maybe ui-select has too.

**Comment by azeyad** [comment]
@petrsimon thanks a lot for pointing me to the right place to search, ui-select does have an option that moves the dropdown element to the end of the body element before opening it, I used it and it works fine so far, for ref. you need to add [append-to-body="true"] to the ui select tag
