### ISSUE TITLE
Instructions for bower are incorrect

### ISSUE THREAD

**Issue by jongunterfv** [angular-ui/ui-layout#171]
In the docs, it says use the command `bower install angular-ui-layout\#bower`
That doesn't work, I got ` Package angular-ui-layout\ not found`

`bower install angular-ui-layout` without the trailing slash and hash seems to work better. I don't know much about Bower, but should you change the docs?

**Comment by SomeKittens** [comment]
We're not supporting Bower anymore, though if you submit a PR, I'll bring it in.
