### ISSUE TITLE
variables not updating in real-time

### ISSUE THREAD

**Issue by theDude30** [angular-ui/ui-layout#172]
Hi,
i want to be able to save current state of the sizes in order to restore it later on.
To do so i will need to get access to the following variables and they need to be bindable:
size
minSize
maxSize

is there a way to expose those variables and have them bindable so they will update in real-time?
is there other way to know the current size state?

**Comment by SomeKittens** [comment]
This functionality is being added here: https://github.com/angular-ui/ui-layout/pull/164
