### ISSUE TITLE
Angular ui-layout toggle not working

### ISSUE THREAD

**Issue by sooryailangovan** [angular-ui/ui-layout#177]
Angular Version - 1.4.7 Ui-Layout Version - 1.4.1 Plunkr Link - http://plnkr.co/edit/S22WaqQRjtSNIPBYlHd7?p=preview

Collapse of section "two" in the plunkr example is not working using the toggle button in the one|two splitter. Likewise Collapse of section "four" in the plunkr example is not working using the toggle button in the three|four splitter. Please help

**Comment by SomeKittens** [comment]
Dupe of #173
