### ISSUE TITLE
uiLayoutLoaded - Error: [$injector:strictdi] function($timeout, Layout)...

### ISSUE THREAD

**Issue by proteye** [angular-ui/ui-layout#186]
Hello.
Error: [$injector:strictdi] function($timeout, Layout) is not using explicit annotation and cannot be invoked in strict mode.

`.directive('uiLayoutLoaded', function($timeout, Layout) ...` - **ERROR**
`.directive('uiLayoutLoaded', ['$timeout', 'Layout', function($timeout, Layout) ...` - **OK**

**Comment by SomeKittens** [comment]
Should be fixed in 1.4.2
