### ISSUE TITLE
CHANGELOG.md not up to date

### ISSUE THREAD

**Issue by synox** [angular-ui/ui-layout#229]
I can not see what changed. Not in CHANGELOG.md and not in https://github.com/angular-ui/ui-layout/releases description.

**Comment by digitaldina** [comment]
it's working for me, let me know if you're still getting this issue.

**Comment by synox** [comment]
https://github.com/angular-ui/ui-layout/blob/master/CHANGELOG.md was not updated. Does not matter, project seems dead anyway.
