### ISSUE TITLE
Initial size of panes/position of splitbar is not always correct

### ISSUE THREAD

**Issue by mindjuice** [angular-ui/ui-layout#47]
Sometimes the splitbar is positioned such that the leftmost pane has size zero.

Here is a Plunker showing the issue.  In this case it's combined with Angular bootstrap-ui's tabset and tab tags, but I've seen it without using these (couldn't manage to reproduce that simpler case just now though -- couldn't remember the combination of layout that caused it).

  http://plnkr.co/wBoCHdMd3VNPYryE1URy

Notice that the leftmost splitbar is all the way to the left, even though there are min-size and size set for the div.

If you click on the splitbar and move it one pixel to the right, it will snap into place.

Debugging this a bit, it seems that tElement[0].offsetWidth is zero (the parent element's size) for some reason.  I'm not that familiar with how/when layout sets this value.

**Comment by SomeKittens** [comment]
Closing this, as the initial issue seems to have been fixed.  Using #100 to track the window resizing issue.  Thanks!
