### ISSUE TITLE
css issues

### ISSUE THREAD

**Issue by qwiglydee** [angular-ui/ui-layout#50]
http://embed.plnkr.co/ydH35oyYRBbRDTgHd0Nk/preview
- shevrons are not visible in sliders
- horizontal slider draws scroller

**Comment by SomeKittens** [comment]
Scrollbar appearing fixed in 051b16408646b7bbd4710a83f0b4311e37f01a5a

Chevron color was fixed in 72da419f0b40ea7d9630a61148191925e9a30daa

Using #100 to track window resizing issue.
