### ISSUE TITLE
Option to hide chevrons on splitbar

### ISSUE THREAD

**Issue by amergin** [angular-ui/ui-layout#56]
Could you provide an option to disable splitbar/divider? It is not always needed.

**Comment by nicklasb** [comment]
Me three. I hid it them by not setting their icon, min/max and dividerSize="0".
    
    .glyphicon-chevron-left,
    .glyphicon-chevron-right
    /*, TODO: Commenting out these until splitters can be hidden in angular-ui-layout
    .glyphicon-chevron-up,
    .glyphicon-chevron-down*/{
      color: #aaa;
    }

**Comment by SomeKittens** [comment]
Do you want to disable the chevrons, have the splitbar not appear, or have it show up but not be movable?

**Comment by nicklasb** [comment]
@SomeKittens : In my case, I wanted to hide them. 
But the most optimal solution for me would be if one could disable them alltogether, for example disable if it is a mobile/table browser where you want the page to be responsive, and enable it for desktop users. 
It is not just the layout, but also the matter that using it without a mouse is difficult.

**Comment by amergin** [comment]
@SomeKittens : in my case I would like to hide the splitbar and chevrons. On the other hand, I can think of use case where a static splitbar without chevrons could come in handy, as well.

**Comment by YugoAmaryl** [comment]
+1
I need to do achieve the same sort of things that jnmoons described.

**Comment by SomeKittens** [comment]
@YugoAmaryl Please don't +1 an issue.  If there isn't an open issue for your problem, open a new one.
