### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by maxkorp** [angular-ui/ui-layout#71]
Currently if I want to grab ui-layout with an NPM install, I have to set it to the github path. This is small, but what makes it frustrating is that the releases that get tagged don't include a package.json, so you have to go dig on master and find the matching commit to a given version, and then set to that, rather than just referencing the tag. I know the package is on bower, but a lot of people don't feel like using 2 package managers for a project, especially if only one or two packages requires the second. 

At minimum, it would be nice to include the package.json in the tagged build. Ideally, that tagged commit would also get published to NPM. I'll throw up a PR in a bit, but I wanted to see if anyone had any input.

**Comment by alvint** [comment]
@jbroquist - The OP answered that question (why NPM) in his original comment, and it's a very good reason. In my case I use Browserify to package my HTML projects (along with Gulp to package the CSS). This works with everything else in the Angular bullpen.

I was very excited to use this package in my projects, but there's no way on Earth I'm going to add a second build system and have some deps work one way and other deps work another way just to get it. Other people have to maintain my projects after I'm done writing them, so I don't want to add extra complexity. Bower is **so** 2013, Grandpa! Please reconsider this.

**Comment by alvint** [comment]
:+1:

**Comment by alvint** [comment]
@maxkorp - How do you set it to the GitHub path?

**Comment by jbroquist** [comment]
@alvint see my response in #72

**Comment by alvint** [comment]
@jbroquist - I see! Are there any instructions on the technique @maxkorp mentioned?

**Comment by maxkorp** [comment]
Sorry, i've been offline a bit. 
To reference a specific commit or tag in your package.json so that NPM can just pull it from github, you have to reference owner/repository#oid, so your dependencies in package.json would look like
```
"dependencies": {
  ...
  "ui-layout": "angular-ui/ui-layout#352bd3c67f2cd5af2be4ab884b91903946409e99",
  ...
}
```
where `352bd3c67f2cd5af2be4ab884b91903946409e99` points to the commit where it was upgraded to 1.0.5, in my case. You have to dig around a bit because simply using the tags put up point to the bower branch, which doesnt include the package.json, so you need to use the master branch which leaves it intact. Unfortunately, that doesnt include the build, so you need to manually cd in and build it. 

As i said in the issue tagged directly above this comment for ui bootstrap, this is best resolved by adding to the angular-ui publishing platform, but I just haven't had the time.

**Comment by maxkorp** [comment]
For reference: https://github.com/angular-ui/angular-ui-publisher/issues/3
