### ISSUE TITLE
Splitting a div that may be longer than the window (North, East+/West+)?

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ui-layout#75]
I love the Holy Grail demo!  

But... it assumes ui-layout will be used to partition the entire visible browser window.  

Is there a way to use it to split a div that may continue beyond the window length?  I'm able to get it to function within a div by using `style="position:relative"` on the parent of the ui-layout, but I don't see how to allow the vertical partitions to extend beyond the bottom of the browser (causing a scrollbar to appear for the entire window). Instead, each partition ends up with its own scrollbar, as needed ... which is ugly.

Think of this as North, East+, and West+, with East+ and West+ potentially longer than the window size.

**Comment by jbroquist** [comment]
You're going to have to provide a plunkr of what you're trying to accomplish. The module should automatically size to any container that has relative positioning. 

Here's an example with a table that extends beyond the page fold and the `ui-layout` sizing to the same size: http://plnkr.co/edit/iiJTbWMEHlpi43iu2teM?p=preview

**Comment by Dev63** [comment]
@jbroquist Here's a [plunker](http://plnkr.co/edit/W5LqatQmr06qNiyXFpCU?p=preview) that provides a simplified view of what I'm trying to do.  The container height needs to vary with the contents, as the content changes or even as I resize a column and the lines wrap differently.

**Comment by SomeKittens** [comment]
This is due to our setting `position: absolute` on each container item so that we can position them correctly on the page.  As much as I'd like this feature, it's incompatible with how we do things currently.  Sorry about that.
