### ISSUE TITLE
The height of nested row in row flow is not calculated correctly (scroll is shown)

### ISSUE THREAD

**Issue by tomasz-sz** [angular-ui/ui-layout#78]
This bug can be found: 
http://plnkr.co/edit/ClUBztAgxWVa0UH58TPf?p=preview

The scroll is shown on the bottom right corner. 

The code to reproduce:

    <div ui-layout  >
      <div ui-layout-container class=" html-back" ></div>
      
      <div ui-layout-container> 
        <div ui-layout="{flow : 'column'}" >
          <div ui-layout-container class=" html-back" ></div>
          <div ui-layout-container >
              <div ui-layout  >
                  <div ui-layout-container class=" html-back" ></div>
                  <div ui-layout-container class=" html-back" ></div>
             </div>
          </div>
        </div>
      </div>
    </div>

**Comment by j--w** [comment]
Plunker link no longer working, will attempt to create another to reproduce.

**Comment by j--w** [comment]
Here is a plunker with markup to reproduce as mentioned by @tomasz-sz , still unable to reproduce though. Tested in IE10, IE11, Chrome, Firefox, Safari
http://embed.plnkr.co/m74b6DTYEXlIQGzg4Oio/

**Comment by SomeKittens** [comment]
Ah!  This is a dupe of #118
