### ISSUE TITLE
Bootstrap container vs ui-layout

### ISSUE THREAD

**Issue by nicklasb** [angular-ui/ui-layout#80]
It doesn't work to put ui-layout inside a `<div class="container">...</div>`.
Is ui-layout always whole-window or am I not getting something?

**Comment by douglasduteil** [comment]
Just wrap the directive inside a tag with a `position: relative` style maybe

**Comment by nicklasb** [comment]
If you mean like this, it didn't work, rather, that caused the entire content to end up outside the window up top. 

    <div class="container">
        <div style="position: relative">
            <ui-layout options="{ flow : 'row' }">
    .. layout...
            </ui-layout>
        </div>
    </div>

Not sure what I can try here. It might be that bootstrap and ui-layout are at odds conceptually, but nevertheless it seems that it should be possible having it work without affecting parent nodes.

**Comment by nicklasb** [comment]
Made some updates through bower, and now it works. I can even set the container directly on the ui-layout tag. Have no real idea why, however I did install the non-angular bootstrap.
Did get this error from bower on ui-layout though, not sure if it signaled an update or was related:

    bower angular-ui-layout#bower      invalid-meta angular-ui-layout is missing "ignore" entry in bower.json
    bower angular-ui-layout#bower          resolved git://github.com/angular-ui/ui-layout.git#26c563e485

Closing this issue, thanks for your support!
