### ISSUE TITLE
Demo plunker for ui.layout is broken

### ISSUE THREAD

**Issue by eswdd** [angular-ui/ui-layout#81]
As linked from the docs: http://plnkr.co/edit/?p=preview

This would be really handy as I'm struggling to get the layout working, and a working plunker would greatly aid.

**Comment by jbroquist** [comment]
Not sure how you got that link, but I copy and pasted the URL linked in the readme file:
http://plnkr.co/zB4mhgJyVz7GlwG8JmeM

**Comment by eswdd** [comment]
Sorry, didn't even notice I'd done that. Link was from http://angular-ui.github.io/ui-layout/ and definitely doesn't work. The one you've provided does. Thanks.

**Comment by jbroquist** [comment]
@

**Comment by douglasduteil** [comment]
To develop on it I'm using this cmd series

```sh
gulp dist && gulp build --branch gh-pages && browser-sync start --server out/built/gh-pages
```
(require `npm i -g gulp browser-sync`)

for the publication on the gh-pages
You can force one with 

```
gulp publish --branch gh-pages
```

or/and you can add this line on the .travis.yml file to auto publish every time the build pass on the master or on a tag.

Let me know if it's working for you.

**Comment by gitfacile** [comment]
Hi guys! I went to plunker from http://angular-ui.github.io/ui-layout/ and it doesn't seem to work although all seems fine. Any ideas why? Also, is it possible to get the code from the holy grail plunk http://plnkr.co/zB4mhgJyVz7GlwG8JmeM?

Thanks!

**Comment by SomeKittens** [comment]
The demo page is grossly out of date - ticket for updating it is here: #119.  The trouble is the directive API for UI Layout has changed and the demo page Plunker has its script tags pointing at latest.

**Comment by theclapp** [comment]
For what it's worth, I built a working plunker referencing the dist code from the demo itself.  See http://plnkr.co/edit/mxbTJO?p=preview.  Whether this does more harm than good is left as an exercise for the reader.

**Comment by SomeKittens** [comment]
@theclapp Nice!  That'll be useful when we get to 119.  Mind posting it over there?

**Comment by theclapp** [comment]
I figured out the version that the demo is using (v0.0.2) and updated the plunker to use that version directly.  So now an update to the dist code won't break it.
