### ISSUE TITLE
Splitbar touch drag does not work when JQuery library present

### ISSUE THREAD

**Issue by groberts9** [angular-ui/ui-layout#82]
Using ui-layout 1.0.5 in Chrome 40 and IOS 8.1 Safari when the JQuery library of any vintage is loaded the splitbar will not move using touch.  I presume this problem will occur with most or all browsers.

For the browsers I am using this can be fixed by changing:

        (mouseEvent.originalEvent && mouseEvent.originalEvent[ctrl.sizeProperties.mouseProperty]) ||

to

        (mouseEvent.originalEvent && mouseEvent.originalEvent.targetTouches[0][ctrl.sizeProperties.mouseProperty]) ||

Apologies for not forking; I don't have time at the moment to learn the necessary skills or test this on all leading browsers.

**Comment by nitech** [comment]
Thank you groberts9. My issue was the exact same

**Comment by SomeKittens** [comment]
Reproduced w/ demo2.htm, fix currently presented breaks tests.
