### ISSUE TITLE
ui-layout-container not compatible with ng-if 

### ISSUE THREAD

**Issue by groberts9** [angular-ui/ui-layout#84]
I am sure the author and major contributors knew about this particular limitation when it was coded, but I needed to get this directive to work with ng-if.

I fixed this problem when ng-if is not on the first ui-layout-container with two botches, as my angular directive skills are not currently sufficient to fix this for all usage requirements and I have to deliver a working solution for a deadline.

There are two problems:

1.  When the ui-layout-container is removed from the DOM, the splitter bar and the updateDisplay() calculation needs to allow for removal.  I added a '$destroy' event to the uiLayoutContainer directive to call a new function ctrl.removeContainer(scope.container) - this removed the container from the collection, and in my case I also hide the related splitter bar element;
2. When ui-layout-container is inserted by ng-if, a splitter bar is needed for the new layout container.  My botch was to unhide the splitter bar I had previously hidden.

When the splitter bar was hidden I adjusted the count of the number of splitter bars.  Note that some care is needed when hiding splitter bars to make sure the chevron buttons appear in the right location.

The better solution would be to "intelligently" insert the a splitter bar element either before or after the ui-layout-container element, depending on the position of this element in a collection of ui-layout-container elements, when the element is added to the DOM; also it would be nice to be able to avoid the requirement to remove the last splitter bar as done by the current implemented.

**Comment by mofojed** [comment]
+1

**Comment by mofojed** [comment]
I've added a pull request for this: #86

**Comment by mofojed** [comment]
Plunkr here: http://plnkr.co/edit/oHO0HeXJPgD4U8NSa2lM?p=preview

**Comment by groberts9** [comment]
Plunkr version works very well.

**Comment by bosco2010** [comment]
+1 thanks for this!

**Comment by faisalferoz** [comment]
+1
