### ISSUE TITLE
v0.0 does not work

### ISSUE THREAD

**Issue by janega** [angular-ui/ui-layout#91]
I cannot for the life of me get the 0.0 version working as I need IE9 support. I get the following error:

Cannot read property 'flow' of undefined 

Which occurs here:

![image](https://cloud.githubusercontent.com/assets/9831985/6828078/1e1d45f2-d2e2-11e4-9066-10f09fc61a88.png)

Any ideas on how I can fix this? Great work on this btw!

**Comment by gpothier** [comment]
Same problem here. I adapted the HTML code from the Holy Grail Demo:
<div ui-layout="{flow : 'row'}"  >
      <div ui-layout-container class=" html-back" ></div>
      
      <div ui-layout-container> 
        <div ui-layout="{flow : 'column'}" >
          <div ui-layout-container class=" html-back" >A</div>
          <div ui-layout-container class=" js-back" >B</div>
          <div ui-layout-container class=" css-back" >C</div>
        </div>
      </div>
    
      <div ui-layout-container class=" css-back" >D</div>
    </div>

I see the panels and their content, but I cannot move the sliders, and I get an error at ui.layout.js:50

**Comment by SomeKittens** [comment]
Can you create a JSBin reproducing this issue?

**Comment by BobbieBarker** [comment]
Closing issue, no follow up, and supporting the 0.0 version isn't on the agenda for this project.
