### ISSUE TITLE
Contents don't appear in print

### ISSUE THREAD

**Issue by darabos** [angular-ui/ui-layout#94]
The contents of the `ui-layout` directive do not show up when printing a page. (At least not in Chrome.)

**Comment by miriam-yodlr** [comment]
I haven't tested this, but my guess is that an @media print rule setting the divs you want to print to "position: static;" should allow the whole contents to display.  They would be stacked in the order of the dom, not partitioned like the page.

**Comment by darabos** [comment]
Thanks! Yes, I had to add `position: static` plus `overflow: visible`. (Sorry I failed to mention this originally.) If that's all it takes, I guess I could try to make a pull request for it. Shall I?

**Comment by SomeKittens** [comment]
@darabos Yes, a PR would be lovely.
