### ISSUE TITLE
Allow sections to have a fixed size

### ISSUE THREAD

**Issue by smart987** [angular-ui/ui-layout#95]
I need to fix the sizes of blocks (like east, west, north and south blocks) in the ui layout. They should not slidable/draggable. Is it possible?

**Comment by Tooa** [comment]
Hi,
in case you are still interested in this: You can use `disableToggle` property and set the min and max size. Should be, what you are looking for. Think this issue can be closed then.

**Comment by SomeKittens** [comment]
Consolidating this with #138
